
#ifndef __TEMPERATURE_LOGGER_CONFIG_H__
#define __TEMPERATURE_LOGGER_CONFIG_H__

#define SCREEN_WIDTH 128
#define SCREEN_HEIGHT 64
#define PLOT_Y_MAX_C 30.0
#define PLOT_Y_MIN_C 15.0
#define PLOT_Y_TOP 16
#define PLOT_Y_BOTTOM (SCREEN_HEIGHT - 5)
#define PLOT_Y_PIXELS (PLOT_Y_BOTTOM - PLOT_Y_TOP)
#define PLOT_X_LEFT 12
#define PLOT_X_RIGHT (SCREEN_WIDTH - 4)
#define PLOT_X_PIXELS (PLOT_X_RIGHT - PLOT_X_LEFT)
#define LOG_LENGTH_BYTES PLOT_X_PIXELS
#define EEPROM_T_LOG_BASE 10
#define EEPROM_LOG_PTR 0
#define DISPLAY_I2C_ADDRESS 0x3C
#define TEMPERATURE_NOT_SET 0xFF
#define PIN_BUTTON_A 5
#define PIN_BUTTON_B 6
#define PIN_PWR_AUX_DEVS 9
#define DISPLAY_MODES 2
#define POWER_SAVE_TIMEOUT_MS 20000
#define RECORD_DATA_INTERVAL_MS 300000 // 5 minutes

#endif